#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config   mouse_follows_focus          off
yabai -m config   focus_follows_mouse          on

yabai -m config   window_origin_display        default
yabai -m config   window_placement             second_child
yabai -m config   window_zoom_persist          on
yabai -m config   window_topmost               off

yabai -m config   window_animation_duration    0.5
yabai -m config   window_animation_frame_rate  120
yabai -m config   window_opacity_duration      0.0

yabai -m config   active_window_opacity        1.0
yabai -m config   normal_window_opacity        0.90
yabai -m config   window_opacity               off

yabai -m config   active_window_border_color   0xE032CD32
yabai -m config   insert_feedback_color        0x00010101
yabai -m config   normal_window_border_color   0xE02d74da

yabai -m config   window_border_width          4
yabai -m config   window_border_radius         10
yabai -m config   window_border_blur           on
yabai -m config   window_border_hidpi          off
yabai -m config   window_border                on
yabai -m config   window_gap                   1

yabai -m config   split_ratio                  0.50
yabai -m config   split_type                   auto
yabai -m config   auto_balance                 off
yabai -m config   top_padding                  1
yabai -m config   bottom_padding               1
yabai -m config   left_padding                 1
yabai -m config   right_padding                1
yabai -m config   window_gap                   1

yabai -m config   layout                       bsp

yabai -m config   mouse_modifier               fn
yabai -m config   mouse_action1                move
yabai -m config   mouse_action2                resize
yabai -m config   mouse_drop_action            swap

# only manage WezTerm and Firefox
yabai -m rule --add app!="^(WezTerm|Firefox Developer Edition)$" manage=off

echo "yabai configuration loaded.."
